### ISSUE TITLE
zemberek-nlp 0.9.2 maven-repo

### ISSUE THREAD

**Issue by taliptayfur** [ahmetaa/turkish-nlp-examples#1]
maven-repo da zemberek-nlp 0.9.2 sürümü olmadığı için turkish-nlp-examples projesi derlenemiyor.

**Comment by ahmetaa** [comment]
Bu hafta içinde 0.9.2 sürümünü yayınlayacağım

**Comment by taliptayfur** [comment]
Teşekkürler.
